// src/styles.js
// Shared design tokens and reusable style objects — imported by every tab
// so the whole app looks consistent without repeating CSS everywhere.

export const colors = {
  indigo: "#22385C",
  indigoDark: "#152840",
  mustard: "#C9932E",
  bg: "#F7F6F2",
  card: "#FFFFFF",
  border: "#E4E1D8",
  text: "#26282B",
  textMuted: "#6B6E73",
  success: "#3A7D5C",
  danger: "#B84C3C",
};

export const styles = {
  app: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    background: colors.bg,
    minHeight: "100vh",
    color: colors.text,
  },
  header: {
    background: colors.indigo,
    color: "#fff",
    padding: "16px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
  },
  brand: { fontSize: 19, fontWeight: 700, letterSpacing: 0.2 },
  tabBar: {
    display: "flex",
    gap: 4,
    padding: "8px 12px",
    background: "#fff",
    borderBottom: `1px solid ${colors.border}`,
    overflowX: "auto",
  },
  tabBtn: (active) => ({
    padding: "9px 14px",
    borderRadius: 8,
    border: "none",
    background: active ? colors.indigo : "transparent",
    color: active ? "#fff" : colors.textMuted,
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
    whiteSpace: "nowrap",
  }),
  main: { padding: 16, maxWidth: 1080, margin: "0 auto" },
  card: {
    background: colors.card,
    border: `1px solid ${colors.border}`,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    flexWrap: "wrap",
    gap: 8,
  },
  h2: { fontSize: 16, fontWeight: 700, margin: 0 },
  label: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: 600,
    display: "block",
    marginBottom: 4,
  },
  input: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    fontSize: 14,
    marginBottom: 12,
    boxSizing: "border-box",
    background: "#fff",
    color: colors.text,
  },
  row2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  row3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 },
  btn: {
    background: colors.indigo,
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 18px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
  },
  btnGhost: {
    background: "transparent",
    color: colors.indigo,
    border: `1px solid ${colors.indigo}`,
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnDanger: {
    background: "transparent",
    color: colors.danger,
    border: `1px solid ${colors.danger}`,
    borderRadius: 8,
    padding: "6px 10px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnWhatsapp: {
    background: "#25D366",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  btnPdf: {
    background: colors.mustard,
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  listItem: {
    border: `1px solid ${colors.border}`,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
  badge: (bg, fg) => ({
    display: "inline-block",
    background: bg,
    color: fg,
    fontSize: 11,
    fontWeight: 700,
    padding: "3px 9px",
    borderRadius: 999,
  }),
  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
  },
  statCard: {
    background: colors.card,
    border: `1px solid ${colors.border}`,
    borderRadius: 12,
    padding: 14,
  },
  statLabel: { fontSize: 12, color: colors.textMuted, fontWeight: 600 },
  statValue: { fontSize: 20, fontWeight: 800, marginTop: 4 },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
  },
  th: {
    textAlign: "left",
    padding: "8px 10px",
    borderBottom: `2px solid ${colors.border}`,
    color: colors.textMuted,
    fontWeight: 700,
    fontSize: 12,
    whiteSpace: "nowrap",
  },
  td: {
    padding: "8px 10px",
    borderBottom: `1px solid ${colors.border}`,
    whiteSpace: "nowrap",
  },
};

export const statusColors = {
  pending: ["#FDF0DA", "#8A5A11"],
  confirmed: ["#E3EEFB", "#1D4E89"],
  partial_dispatch: ["#F0E7FB", "#5B3A94"],
  fulfilled: ["#E4F4EA", "#237A4B"],
  closed: ["#E8E8E8", "#4A4A4A"],
  cancelled: ["#FBE6E4", "#A5301F"],
};
